mod block;

pub use block::Block;

use crate::types::BlockVec;

/// Block view generated by builders.
#[derive(Debug, Clone, Default)]
pub struct BV {
  pub blocks: Vec<Block>,
  pub width: BlockVec,
  pub height: BlockVec
}
