[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "Unlicense"
repository = "https://github.com/Resonaa/polygen"
homepage = "https://161.moe"

[workspace.dependencies]
bitfield-struct = "0.10.0"
glam = { version = "0.29.2", features = ["fast-math"] }
rand = "0.8.5"
wasm-bindgen = "0.2.100"
getrandom = { version = "0.2.15", features = ["js"] }
rand_chacha = "0.3.1"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
