name = "polygen"
compatibility_date = "2025-06-13"
workers_dev = false

[env.production]
routes = [{ pattern = "161.moe", custom_domain = true }]

[env.development]
routes = [{ pattern = "dev.161.moe", custom_domain = true }]

[assets]
directory = "./packages/ui/dist/"
not_found_handling = "single-page-application"
