name = "polygen"
compatibility_date = "2025-06-13"
route = "161.moe/*"

[env.development]
route = "dev.161.moe/*"

[assets]
directory = "./packages/ui/dist/"
not_found_handling = "single-page-application"
