[package]
name = "algorithm"
version = "0.1.0"
readme = "../../README.md"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
anyhow.workspace = true
model = { path = "../model" }
rand.workspace = true
thiserror.workspace = true
