name: Deploy

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_VERBOSE: "true"
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Rust toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install wasm-pack
        run: bun install -g wasm-pack

      - name: Install dependencies
        run: bun install

      - name: Build WebAssembly package
        run: bun wasm

      - name: Build for production
        run: bun release

      - name: Configure environment
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "CLOUDFLARE_ENV=production" >> $GITHUB_ENV
          else
            echo "CLOUDFLARE_ENV=development" >> $GITHUB_ENV
          fi

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ env.CLOUDFLARE_ENV }}
